linters:
  enable:
    - errorlint
    - forbidigo
    - gochecknoinits
    - gocritic
    - goconst
    - gocyclo
    - goimports
    - misspell
    - revive
    - unconvert
    - unparam
    - wastedassign

linters-settings:
  gocyclo:
    min-complexity: 17
  gofumpt:
    extra-rules: true
  govet:
    enable-all: true
    disable:
      - fieldalignment